import React, { useEffect, useState,useRef } from 'react'
import QuiltedImage from '../components/QuiltedImage';
import DialogBox from '../components/DialogBox';
import fetchApi from '../functions/fetchApi';
import onScroll from '../functions/onScroll';
import handleDisplay from '../functions/handleDisplay'



const Home = ({ itemData, setItemData, Fetching, setLoggedIn, loggedin }) => {

  let index = useRef(null)

  const [cur, setCur] = useState({
    open: false,
    data: ''
  })

  useEffect(() => {
    document.addEventListener('scroll', (event) => onScroll(event, index, Fetching, setLoggedIn, setItemData))
    return () => document.removeEventListener('scroll', (event) => onScroll())
  }, [])

  useEffect(() => {
    if (loggedin) {
      if (!Fetching.current) {
        Fetching.current = true
        fetchApi(index, Fetching, setLoggedIn, setItemData)
      }
    }
  }, [])

  return (
    <div className='w-[70%] ml-[15%] h-[90%]'>
      <div className='mb-[100px] mt-[50px]'>
        <h1 className='text-4xl font-medium'>The Community Showcase</h1>
        <p className='text-slate-500 pt-4'>Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
      </div>
      <QuiltedImage setCur={setCur} itemData={itemData} />
      {
        cur &&
        <DialogBox
          open={cur.open}
          data={cur.data}
          display={() => handleDisplay(setCur)}
          prompt={cur.prompt}
          creator={cur.name}
          setItemData={setItemData}
        />
      }
    </div>
  )
}

export default Home;